name: KanaChat
version: 2.1.2a
authors: [ fubira, 月見里 彩葉 ]
contributors: [ Shotadft ]
main: net.ironingot.kanachat.KanaChat
api-version: '1.21'
description: Alphabet to Hiragana convert + Kanji Translation
website: 'https://github.com/yanashi-interface/KanaChat/'
commands:
  kanachat:
    aliases:
      - japanize
      - kc
    usage: |
      /<command> [on|off] 
      /<command> kanji [on|off]
      /<command> dict list
      /<command> dict add <word> <alphabet...>
      /<command> dict edit <word> <alphabet...>
      /<command> dict remove <word>
    description: Enable or Disable roma-ji japanese translation
